### ISSUE TITLE
Write TypeScript scripts interacting with Todoist

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#17]
Write TypeScript (Bun) scripts interacting with Todoist for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 42 scripts. You can find all the script descriptions in src/integrations.yaml.

Full instructions on how to do this can be found in the README.md file.

Get started by running `bun run setup todoist`.

**Comment by abhishek818** [comment]
@HugoCasa  adding myself in queue.
