### ISSUE TITLE
Write TypeScript scripts interacting with Google Cloud

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#18]
Write TypeScript (Bun) scripts interacting with Google Cloud for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 11 scripts. You can find all the script descriptions in src/integrations.yaml.

Full instructions on how to do this can be found in the README.md file.

Get started by running `bun run setup gcloud`.

**Comment by abhishek818** [comment]
@HugoCasa  can you assign this to me?

**Comment by abhishek818** [comment]
@HugoCasa , have opened a [PR](https://github.com/windmill-labs/windmill-community-integrations/pull/23).

**Comment by mojitomoise** [comment]
/attempt https://github.com/windmill-labs/windmill-community-integrations/issues/18

**Comment by feliciien** [comment]
Hello need api.accelo.com tokens

**Comment by feliciien** [comment]
In the context of our Windmill Hub project, we're looking to integrate functionality to add members to a mailing list using Mailgun. Would you recommend a specific approach or provide guidance on how we can seamlessly integrate this Mailgun functionality alongside our existing scripts interacting with Google Cloud services?
