### ISSUE TITLE
Write TypeScript scripts interacting with LinkedIn

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#19]
Write TypeScript (Bun) scripts interacting with LinkedIn for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 17 scripts. You can find all the script descriptions in src/integrations.yaml.

Full instructions on how to do this can be found in the README.md file.

Get started by running `bun run setup linkedin`.

**Comment by abhishek818** [comment]
Was giving it a try, Seems there are issues with "https://api.linkedin.com/v2/userinfo" or "https://api.linkedin.com/v2/me" (required apis to get userId)

**Comment by abhishek818** [comment]
got some lead, @HugoCasa  can you assign it to me?

**Comment by ezhil56x** [comment]
Can I get this assigned?

**Comment by abhishek818** [comment]
@HugoCasa  hey, you unassigned me??
