### ISSUE TITLE
Write TypeScript scripts interacting with Quickbooks

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#2]
Write TypeScript (Bun) scripts interacting with Quickbooks for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 26 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup quickbooks`.

**Comment by rajdip-b** [comment]
Hey @tobihans, I was discussing the issue with @HugoCasa over discord and totally forgot to make the attempt. Mind if I take up this one?

**Comment by tobihans** [comment]
No problem @rajdip-b, go ahead !

**Comment by rajdip-b** [comment]
Thanks bro!
