### ISSUE TITLE
Write TypeScript scripts interacting with Pushover

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#20]
Write TypeScript (Bun) scripts interacting with Pushover for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 15 scripts. You can find all the script descriptions in src/integrations.yaml.

Full instructions on how to do this can be found in the README.md file.

Get started by running `bun run setup pushover`.

**Comment by rajdip-b** [comment]
on it
