### ISSUE TITLE
Octokit added to integration boilerplate by default

### ISSUE THREAD

**Issue by rajdip-b** [windmill-labs/windmill-community-integrations#3]
![image](https://github.com/windmill-labs/windmill-community-integrations/assets/83924254/4f585ee8-3fe2-4d76-aae2-d754152d579f)

The GitHub integration uses the `octokit` package, but importing it by default in any boilerplate sound off. We might want to omit [this](https://github.com/windmill-labs/windmill-community-integrations/blob/main/src/index.ts#L98) line from `setup.ts` in `src/`

**Comment by HugoCasa** [comment]
fixed with baac91b
thanks for the report!
