### ISSUE TITLE
Write TypeScript scripts interacting with Zoom

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#5]
Write TypeScript (Bun) scripts interacting with Zoom for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 15 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup zoom`.

**Comment by neo773** [comment]
Can I get assigned?

**Comment by abhishek818** [comment]
@neo773  you active on this ?  Else, I can take this up.

**Comment by neo773** [comment]
@abhishek818 
Yes, I’m active on it
