### ISSUE TITLE
Write TypeScript scripts interacting with Typeform

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#6]
Write TypeScript (Bun) scripts interacting with Typeform for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 12 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup typeform`.

**Comment by rajdip-b** [comment]
/attempt #6 @HugoCasa can you assign this to me?
