### ISSUE TITLE
Write TypeScript scripts interacting with Reddit

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#7]
Write TypeScript (Bun) scripts interacting with Reddit for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 5 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup reddit`.

**Comment by rajdip-b** [comment]
@tarunrajput are you still on it?

**Comment by rajdip-b** [comment]
Okay!
