### ISSUE TITLE
Write TypeScript scripts interacting with Google Forms

### ISSUE THREAD

**Issue by HugoCasa** [windmill-labs/windmill-community-integrations#9]
Write TypeScript (Bun) scripts interacting with Google Forms for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 6 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup gforms`.

**Comment by ezhil56x** [comment]
Can I get this assigned?
/attempt #9
